BiomeChanger:
  PLAINS:
    #Replace biomes that under this commit to plains.
    - PLAINS
#  FOREST:
#    #Replace biomes that under this commit to forest.
#    - JUNGLE
#  SWAMPLAND:
#    #Replace biomes that under this commit to swampland.
#    - JUNGLE_EDGE
#    - JUNGLE_HILLS
#  RIVER:
#    #Replace all biomes to river.
#    - ALL


#Biome List
#   ALL
#   OCEAN
#   PLAINS
#   DESERT
#   EXTREME_HILLS
#   FOREST
#   TAIGA
#   SWAMPLAND
#   RIVER
#   HELL
#   SKY
#   FROZEN_OCEAN
#   FROZEN_RIVER
#   ICE_FLATS
#   ICE_MOUNTAINS
#   MUSHROOM_ISLAND
#   MUSHROOM_ISLAND_SHORE
#   BEACHES
#   DESERT_HILLS
#   FOREST_HILLS
#   TAIGA_HILLS
#   SMALLER_EXTREME_HILLS
#   JUNGLE
#   JUNGLE_HILLS
#   JUNGLE_EDGE
#   DEEP_OCEAN
#   STONE_BEACH
#   COLD_BEACH
#   BIRCH_FOREST
#   BIRCH_FOREST_HILLS
#   ROOFED_FOREST
#   TAIGA_COLD
#   TAIGA_COLD_HILLS
#   MEGA_TAIGA
#   MEGA_TAIGA_HILLS
#   EXTREME_HILLS_PLUS
#   SAVANNA
#   SAVANNA_ROCK
#   MESA
#   MESA_ROCK
#   MESA_CLEAR_ROCK
#   SMALL_END_ISLANDS
#   END_MIDLANDS
#   END_HIGHLANDS
#   END_BARRENS
#   WARM_OCEAN
#   LUKEWARM_OCEAN
#   COLD_OCEAN
#   DEEP_WARM_OCEAN
#   DEEP_LUKEWARM_OCEAN
#   DEEP_COLD_OCEAN
#   DEEP_FROZEN_OCEAN
#   VOID
#   MUTATED_PLAINS
#   MUTATED_DESERT
#   MUTATED_EXTREME_HILLS
#   MUTATED_FOREST
#   MUTATED_TAIGA
#   MUTATED_SWAMPLAND
#   MUTATED_ICE_FLATS
#   MUTATED_JUNGLE
#   MUTATED_JUNGLE_EDGE
#   MUTATED_BIRCH_FOREST
#   MUTATED_BIRCH_FOREST_HILLS
#   MUTATED_ROOFED_FOREST
#   MUTATED_TAIGA_COLD
#   MUTATED_REDWOOD_TAIGA
#   MUTATED_REDWOOD_TAIGA_HILLS
#   MUTATED_EXTREME_HILLS_PLUS
#   MUTATED_SAVANNA
#   MUTATED_SAVANNA_ROCK
#   MUTATED_MESA
#   MUTATED_MESA_ROCK
#   MUTATED_MESA_CLEAR_ROCK
#   BAMBOO_JUNGLE
#   BAMBOO_JUNGLE_HILLS
#   SOUL_SAND_VALLEY
#   CRIMSON_FOREST
#   WARPED_FOREST
#   BASALT_DELTAS

#Do not change this
Version: 1
Command_Aliases: [biomereplacer,br]